function  Book_AddFiles()
{
  this.fNewFile("Using This Help File","Preface.html");
  this.fNewFile("Typographical Conventions","Preface2.html");
  this.fNewFile("1 Quick Start","jquikstart.html");
  this.fNewFile("Connecting to a Database","jquikstart2.html");
  this.fNewFile("2 Using the SQL Server 2000 Driver for JDBC","usejdbc.html");
  this.fNewFile("About the SQL Server 2000 Driver for JDBC","usejdbc2.html");
  this.fNewFile("Connecting Through the JDBC Driver Manager","usejdbc3.html");
  this.fNewFile("Connecting Through Data Sources","usejdbc4.html");
  this.fNewFile("Specifying Connection Properties","usejdbc5.html");
  this.fNewFile("Using the SQL Server 2000 Driver for JDBC on a Java 2 Platform","usejdbc6.html");
  this.fNewFile("Error Handling","usejdbc7.html");
  this.fNewFile("SQL Server 2000 Driver for JDBC Directory Structure","usejdbc8.html");
  this.fNewFile("3 SQL Server 2000 Driver for JDBC","jdbcsqlsrv.html");
  this.fNewFile("Data Source and Driver Classes","jdbcsqlsrv2.html");
  this.fNewFile("Connection String Properties","jdbcsqlsrv3.html");
  this.fNewFile("Connecting to Named Instances","jdbcsqlsrv4.html");
  this.fNewFile("Data Types","jdbcsqlsrv5.html");
  this.fNewFile("SQL Escape Sequences","jdbcsqlsrv6.html");
  this.fNewFile("Isolation Levels","jdbcsqlsrv7.html");
  this.fNewFile("Using Scrollable Cursors","jdbcsqlsrv8.html");
  this.fNewFile("Installing Stored Procedures for JTA","jdbcsqlsrv9.html");
  this.fNewFile("A JDBC Support","jdbcsupp.html");
  this.fNewFile("Supported Functionality","jdbcsupp2.html");
  this.fNewFile("jdbcsupp3.html","jdbcsupp3.html");
  this.fNewFile("jdbcsupp4.html","jdbcsupp4.html");
  this.fNewFile("jdbcsupp5.html","jdbcsupp5.html");
  this.fNewFile("jdbcsupp6.html","jdbcsupp6.html");
  this.fNewFile("jdbcsupp7.html","jdbcsupp7.html");
  this.fNewFile("jdbcsupp8.html","jdbcsupp8.html");
  this.fNewFile("jdbcsupp9.html","jdbcsupp9.html");
  this.fNewFile("jdbcsupp10.html","jdbcsupp10.html");
  this.fNewFile("jdbcsupp11.html","jdbcsupp11.html");
  this.fNewFile("jdbcsupp12.html","jdbcsupp12.html");
  this.fNewFile("jdbcsupp13.html","jdbcsupp13.html");
  this.fNewFile("jdbcsupp14.html","jdbcsupp14.html");
  this.fNewFile("jdbcsupp15.html","jdbcsupp15.html");
  this.fNewFile("jdbcsupp16.html","jdbcsupp16.html");
  this.fNewFile("jdbcsupp17.html","jdbcsupp17.html");
  this.fNewFile("jdbcsupp18.html","jdbcsupp18.html");
  this.fNewFile("B SQL Server 2000 Driver for JDBC GetTypeinfo","getinfoapp.html");
  this.fNewFile("C Designing JDBC Applications for Performance Optimization","jdbcdesign.html");
  this.fNewFile("Using Database Metadata Methods","jdbcdesign2.html");
  this.fNewFile("Retrieving Data","jdbcdesign3.html");
  this.fNewFile("Retrieving Long Data","jdbcdesign4.html");
  this.fNewFile("Selecting JDBC Objects and Methods ","jdbcdesign5.html");
  this.fNewFile("Designing JDBC Applications","jdbcdesign6.html");
  this.fNewFile("Updating Data","jdbcdesign7.html");
  this.fNewFile("Conclusion ","jdbcdesign8.html");
  this.fNewFile("D SQL Escape Sequences for JDBC","scalarfn.html");
  this.fNewFile("Date, Time, and Timestamp Escape Sequences","scalarfn2.html");
  this.fNewFile("Scalar Functions","scalarfn3.html");
  this.fNewFile("Outer Join Escape Sequences","scalarfn4.html");
  this.fNewFile("Procedure Call Escape Sequences","scalarfn5.html");
}
