function  Book_AddIndexEntries(ParamIndex)
{
  ParamIndex.fSetTotalEntries(256);

  ParamIndex.fAddEntry("connecting	data sources", new Array("usejdbc4.html#539865"));
  ParamIndex.fAddEntry("connecting	JDBC driver manager", new Array("usejdbc3.html#548419"));
  ParamIndex.fAddEntry("connecting	specifying connection properties", new Array("usejdbc5.html#539920"));
  ParamIndex.fAddEntry("connecting", new Array());
  ParamIndex.fAddEntry("connection pooling, using", new Array("usejdbc4.html#539893"));
  ParamIndex.fAddEntry("conventions, typographical", new Array("Preface2.html#1028391"));
  ParamIndex.fAddEntry("data sources	calling in an application", new Array("usejdbc4.html#539880"));
  ParamIndex.fAddEntry("data sources	implementing", new Array("usejdbc4.html#539867"));
  ParamIndex.fAddEntry("data sources	using connection pooling", new Array("usejdbc4.html#539893"));
  ParamIndex.fAddEntry("data sources", new Array());
  ParamIndex.fAddEntry("data types, SQL Server 2000 Driver for JDBC", new Array("jdbcsqlsrv5.html#920597"));
  ParamIndex.fAddEntry("database errors", new Array("usejdbc7.html#539434"));
  ParamIndex.fAddEntry("date, time, timestamp", new Array("scalarfn2.html#17272"));
  ParamIndex.fAddEntry("designing JDBC applications. See performance optimization", new Array("jdbcdesign.html#68625"));
  ParamIndex.fAddEntry("driver manager", new Array("usejdbc3.html#548419"));
  ParamIndex.fAddEntry("error handling", new Array("usejdbc7.html#539409"));
  ParamIndex.fAddEntry("getTypeinfo", new Array("getinfoapp.html#918106"));
  ParamIndex.fAddEntry("isolation levels, SQL Server 2000 Driver for JDBC", new Array("jdbcsqlsrv7.html#915171"));
  ParamIndex.fAddEntry("JDBC data sources. See data sources", new Array("usejdbc4.html#539865"));
  ParamIndex.fAddEntry("JDBC driver manager", new Array("usejdbc3.html#548419"));
  ParamIndex.fAddEntry("JDBC support", new Array("jdbcsupp.html#524304"));
  ParamIndex.fAddEntry("JTA, SQL Server", new Array("jdbcsqlsrv9.html#920336"));
  ParamIndex.fAddEntry("named instances", new Array("jdbcsqlsrv4.html#922593"));
  ParamIndex.fAddEntry("outer join", new Array("scalarfn4.html#29048"));
  ParamIndex.fAddEntry("performance optimization	designing JDBC applications", new Array("jdbcdesign6.html#72586"));
  ParamIndex.fAddEntry("performance optimization	general", new Array("jdbcdesign.html#68625"));
  ParamIndex.fAddEntry("performance optimization	retrieving data", new Array("jdbcdesign3.html#72549"));
  ParamIndex.fAddEntry("performance optimization	retrieving long data", new Array("jdbcdesign4.html#72523"));
  ParamIndex.fAddEntry("performance optimization	selecting JDBC objects and methods", new Array("jdbcdesign5.html#72444"));
  ParamIndex.fAddEntry("performance optimization	updating data", new Array("jdbcdesign7.html#73681"));
  ParamIndex.fAddEntry("performance optimization	using database metadata methods", new Array("jdbcdesign.html#74200"));
  ParamIndex.fAddEntry("performance optimization", new Array());
  ParamIndex.fAddEntry("procedure call", new Array("scalarfn5.html#27367"));
  ParamIndex.fAddEntry("scalar functions", new Array("scalarfn3.html#17303"));
  ParamIndex.fAddEntry("SQL escape sequences	date, time, timestamp", new Array("scalarfn2.html#17272"));
  ParamIndex.fAddEntry("SQL escape sequences	general", new Array("scalarfn.html#17262"));
  ParamIndex.fAddEntry("SQL escape sequences	outer join", new Array("scalarfn4.html#29048"));
  ParamIndex.fAddEntry("SQL escape sequences	procedure call", new Array("scalarfn5.html#27367"));
  ParamIndex.fAddEntry("SQL escape sequences	scalar functions", new Array("scalarfn3.html#17303"));
  ParamIndex.fAddEntry("SQL escape sequences", new Array());
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	connecting to named instances", new Array("jdbcsqlsrv4.html#922593"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	data types", new Array("jdbcsqlsrv5.html#920597"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	directory structure", new Array("usejdbc8.html#998888"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	errors", new Array("usejdbc7.html#539426"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	general", new Array("usejdbc.html#998538"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	isolation levels", new Array("jdbcsqlsrv7.html#915171"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	using on a Java 2 platform", new Array("usejdbc6.html#537191"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC	using scrollable cursors", new Array("jdbcsqlsrv8.html#920960"));
  ParamIndex.fAddEntry("SQL Server 2000 Driver for JDBC", new Array());
  ParamIndex.fAddEntry("SQL Server, JTA", new Array("jdbcsqlsrv9.html#920336"));
  ParamIndex.fAddEntry("URL", new Array("usejdbc3.html#548419"));
  ParamIndex.fAddEntry("using scrollable cursors, SQL Server 2000 Driver for JDBC", new Array("jdbcsqlsrv8.html#920960"));
}
